Numpy- It is an array processing package. It has tools for working with arrays.
It provide efficient storage, uses relatively less memory to story data

In [11]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable



[notice] A new release of pip is available: 25.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [12]:
import numpy as np

lst = [[1, 2, 3, 4, 5]]
arr = np.array(lst, dtype=np.int32)
print(arr)

[[1 2 3 4 5]]


In [13]:
arr.shape #1d array

(1, 5)

In [14]:
arr.dtype

dtype('int32')

In [15]:
arr[0,1]= 45
arr

array([[ 1, 45,  3,  4,  5]], dtype=int32)

In [16]:
lst1= [1,2,3,4,5]
lst2= [6,7,8,9,10]
lst3= [10,11,12,13,14]

arr= np.array([lst1, lst2, lst3])
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [10, 11, 12, 13, 14]])

In [17]:
arr[0:2,0:3]
# from which row to which row and same w colmn

array([[1, 2, 3],
       [6, 7, 8]])

In [18]:
arr.shape

(3, 5)

In [19]:
arr.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 10, 11],
       [12, 13, 14]])

In [20]:
#indexing
arr= np.array([2,4,6,8])
arr[3]

np.int64(8)

In [21]:
arr1=[1,2,3,4,5,6,7,8,9,10]
arr1= np.arange(0, 10, step=2) #start, stop, step(gap)
arr1

array([0, 2, 4, 6, 8])

In [37]:
lspace = np.linspace(1,10,50)
#between 1 to 10 fifty points

In [ ]:
emp_like= np.empty_like(lspace)
emp_like #now we can change places of elements this is for efficiency

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [ ]:
ide= np.identity(50) #identity matrix
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]], shape=(50, 50))

In [ ]:
arr2.ravel() #make the 2d matrix look good (into 1d)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

<!-- 1D array needs 1 axis [Axis0]
2D array needs 2 axises [Axis0][Axis1] -->

In [50]:
x= [[1,2,3], [4,5,6], [7,1,0]]
ar= np.array(x)
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [51]:
ar.sum(axis=0)

array([12,  8,  9])

In [52]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [ ]:
ar.T #transpose= row is colnumn now and vice versa

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [54]:
ar.flat

In [56]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [ ]:
ar.ndim #number of dimensions

2

In [ ]:
ar.size #number of elements

9

In [60]:
ar.nbytes #number of bytes consumed

72

In [64]:
one= np.array([1,32,4,5,28])
one.argmax() #gives index when max element exists

np.int64(1)

In [65]:
one.argsort() #gives the element indexes that if they were they it would have been sorted

array([0, 2, 3, 4, 1])

In [68]:
ar1= np.array([[1,2,3], [4,2,5], [9,4,10]])
ar2= np.array([[2,4,3], [3,7,5], [8,6,3]])

In [69]:
ar1+ar2

array([[ 3,  6,  6],
       [ 7,  9, 10],
       [17, 10, 13]])

In [70]:
ar1*ar2

array([[ 2,  8,  9],
       [12, 14, 25],
       [72, 24, 30]])

In [71]:
np.sqrt(ar1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 1.41421356, 2.23606798],
       [3.        , 2.        , 3.16227766]])

In [73]:
ar.sum()

np.int64(29)

In [74]:
ar.max()

np.int64(7)

In [75]:
np.where(ar>5)

(array([1, 2]), array([2, 0]))

In [77]:
np.nonzero(ar1)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1, 2]))

In [23]:
#copy/ broadcasting fun meaning after 0 index change every element to zero
arr[0:]= 10 
arr

array([10, 10, 10, 10])

In [24]:
arr2=[1,2,3,4,5,6,7,8,9,10]
arr3= arr2.copy() #copy is created
arr3
arr2*2 


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [25]:
arr2 = np.array(arr2)

In [ ]:
arr2[arr2<6] #gives the elements w that condition

array([1, 2, 3, 4, 5])

In [27]:
np.ones(20, dtype=int) #makes all numbers 1s and dtype is the data type u will get as an answer

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [28]:
np.ones((2,5), dtype=int) #matrix

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
emp= np.empty((3,4)) #random elements
emp

array([[1.28440663e-311, 3.16202013e-322, 0.00000000e+000,
        0.00000000e+000],
       [1.78022341e-306, 2.83042415e-056, 2.19223054e-076,
        6.82037847e-038],
       [9.35447802e-067, 2.61998915e+180, 4.79705488e+174,
        4.08387075e-033]])

In [29]:
#finds random values for the matrix
np.random.rand(4,5)

array([[0.46258891, 0.35951447, 0.03954695, 0.76528044, 0.11956157],
       [0.51897882, 0.07946138, 0.59012898, 0.58787198, 0.96302284],
       [0.15553678, 0.93971013, 0.27503685, 0.192539  , 0.11889961],
       [0.0851384 , 0.30693338, 0.9228081 , 0.72912326, 0.89942425]])

In [30]:
np.random.randn(4,5) # n- standard normal distribution

array([[-0.70797967, -1.7713085 , -0.75773712,  1.40817287,  1.06140053],
       [-0.07549965,  0.84752303, -0.79596534, -0.69259963, -0.61343199],
       [ 0.3053518 ,  0.52702739, -0.3473584 , -0.51143905, -0.01902651],
       [ 0.83780497, -2.40927022, -0.30957545,  1.71220492, -0.10479083]])

In [31]:
np.random.randint(0, 100, 30) #selects random int between 1 and 100

array([57, 97, 74, 78, 42, 62, 96, 76, 16, 71, 15, 29, 67, 98, 75, 62, 99,
       59, 41, 12, 16, 76, 49, 39, 13, 23, 34, 73,  6, 31], dtype=int32)

In [32]:
np.random.random_sample((1,5))

array([[0.29099714, 0.33865225, 0.04112356, 0.78115898, 0.1478747 ]])